// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZj-WILWU-sWlibwS1mpwXwHa08MHrPKg',
    appId: '1:942017738617:web:729ff0346b09c11b2461a8',
    messagingSenderId: '942017738617',
    projectId: 'muevete-rico-3544f',
    authDomain: 'muevete-rico-3544f.firebaseapp.com',
    storageBucket: 'muevete-rico-3544f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiy96hhMDmNzBBH5yE_2j6omn2tyFBSs',
    appId: '1:942017738617:android:b7eba6f1039bf0f22461a8',
    messagingSenderId: '942017738617',
    projectId: 'muevete-rico-3544f',
    storageBucket: 'muevete-rico-3544f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJjWO5Gfm26vOzZnCsyXiWvLCk5Lvn5vo',
    appId: '1:942017738617:ios:8118adf72c761ca62461a8',
    messagingSenderId: '942017738617',
    projectId: 'muevete-rico-3544f',
    storageBucket: 'muevete-rico-3544f.firebasestorage.app',
    iosBundleId: 'com.example.muevete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJjWO5Gfm26vOzZnCsyXiWvLCk5Lvn5vo',
    appId: '1:942017738617:ios:8118adf72c761ca62461a8',
    messagingSenderId: '942017738617',
    projectId: 'muevete-rico-3544f',
    storageBucket: 'muevete-rico-3544f.firebasestorage.app',
    iosBundleId: 'com.example.muevete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZj-WILWU-sWlibwS1mpwXwHa08MHrPKg',
    appId: '1:942017738617:web:f373f5dcd4b683b02461a8',
    messagingSenderId: '942017738617',
    projectId: 'muevete-rico-3544f',
    authDomain: 'muevete-rico-3544f.firebaseapp.com',
    storageBucket: 'muevete-rico-3544f.firebasestorage.app',
  );
}
